config/routes.rb
Rails.application.routes.draw do
  
  get 'infos/aboutus'

  get 'infos/contact'

  root 'sessions#new'
  
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  
  
  resources :users, only: [:new, :create, :edit] 
  
  resources :sessions, only: [:new, :create, :destroy]
 
  resources :ingredients
  

  
  
  get 'recipes/index'
  
  get 'recipes/show'
  
  get 'recipes/practice'

end

app/models/ability.rb
class Ability
  
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #user-> current_user
    
    user ||= User.new # guest user (not logged in)
      if user.has_role? :admin 
        #어드민 권한 
        can :manage, :all
      else
        #소시민 권한 
        can :read, :all
        can :new, :all
        can :create, :all 
        can :manage, Ingredient, user_id: user.id
      end
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
    
    belongs_to :user
    
end

app/models/item.rb
class Item < ActiveRecord::Base

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true
            

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
 rolify   
   has_secure_password
   has_many  :ingredients
   validates :nickname, uniqueness: true
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
  
  # def current_user
  #   if @current_user.nil
  #       @current_user = User.find_by(id: session[:user_id])
  #   else
  #       @current_user = @current_user
  #   end
  # end
  
  helper_method :current_user
  
  def authorize
    if current_user.nil?
      redirect_to login_url
    elsif current_user != Ingredient.find(params[:id]).user
      redirect_to root_url
    end
  end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def aboutus
  end

  def contact
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  
  before_action :authorize, only: [ :new, :create, :edit, :update]
  #load_and_authorize_resource
  
  def index
    @items = Item.all 
    @ingredient = Ingredient.new 
  end  
  
  def show
    #@ingredients = Ingredient.all
    #@ingredient = Ingredient.find(params[:id])
    
    @selected_pick = [] 
    @recipes = Recipe.all
    # @recipes = [["meat pie",["a","b","c",d","e","f"],"link"],["second_recipe",["a","b","3","4","5","6"],"link"]]
      user_select = Ingredient.last.s_ingred.split(',')
      # user_select = ["a","b","qqq","wwww"]
     
    @recipes.each do |r|
      ingred_list = r.ingred.gsub(/\"/, '').sub(/\[/,'').sub(/\]/,'').gsub(/ /,'').split(',') 
      s_num = ingred_list.length
      p_num = 0
      user_select.each do |item|
        if ingred_list.include?(item)
          p_num += 1
        end
      end
        
        if (p_num/s_num.to_f) > 0.4 && (p_num/s_num.to_f) <= 1
            @selected_pick << [r,(p_num/s_num.to_f)] 
        end 
    end
        
  end

  
  def create
    # ingredients = Ingredient.new(ingredient_params)
    # ingredients.save
    # redirect_to ingredient_path(ingredients)
    
    
    
    @result = params[:ingredient][:s_ingred] # @result => array형식임
    
    # @ingredient = Ingredient.new
    # @ingredient.s_ingred = @result.join(',')
    Ingredient.create(s_ingred: @result.join(','), user_id: current_user.id)
    # @ingredient.user_id = current_user.id
    
    # @ingredient.save
    
    redirect_to '/ingredients/show'
    
  end

  def new
    @items = Item.all
    @ingredient = Ingredient.new
    
    @a = Ingredient.where(user_id: current_user.id)
    
    
    # authorize! :update, @ingredient

  end
  
  
  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update(post_params)
    redirect_to root_path
  end  
  

  
  
  
  private
  
  def authorize
  redirect_to new_session_path if current_user.nil? 
  end
  
  def ingredient_params
    params.require(:ingredient).permit(:user_id, :s_category, :s_ingred => [])
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  require 'open-uri'
  require 'uri' 
  require 'net/http'
  
  def index
    @recipes = Recipe.all
    @Items = Item.all
    
    page2 = Nokogiri::HTML(open("http://haemukja.com/recipes/1253"))
    @img_link_temp = page2.css('ul.slides img')

  end
  
def show
    #@ingredients = Ingredient.all
    #@ingredient = Ingredient.find(params[:id])
    
    @selected_pick = [] 
    @recipes = Recipe.all
    # @recipes = [["meat pie",["a","b","c",d","e","f"],"link"],["second_recipe",["a","b","3","4","5","6"],"link"]]
      user_select = Ingredient.last.s_ingred.split(',')
      # user_select = ["a","b","qqq","wwww"]
     
    @recipes.each do |r|
      ingred_list = r.ingred.gsub(/\"/, '').sub(/\[/,'').sub(/\]/,'').gsub(/ /,'').split(',') 
      s_num = ingred_list.length
      p_num = 0
      user_select.each do |item|
        if ingred_list.include?(item)
          p_num += 1
        end
      end
        
        if (p_num/s_num.to_f) > 0.4
            @selected_pick << [r,(p_num/s_num.to_f)] 
        end 
    end
        
  end


  def practice
   @selected_pick = [] 
    # @recipes = Recipe.all
    @recipes = [["meat pie",["a","1","c","d","e","f"],"link"],["second_recipe",["a","b","3","4","5","6"],"link"]]
      #user_select = Ingredient.last.s_ingred
      user_select = ["a","b","qqq","wwww"]
      
    @recipes.each do |r|
      s_num = user_select.length
      user_select.each do |item|
        if r[1].include?(item)
          s_num -= 1
        end
      end
        
      if s_num < 3
          @selected_pick << r 
      end 
    end
  end
  
end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
def new
end




def create
    user = User.find_by(nickname: params[:nickname]) 
  if user && user.authenticate(params[:password])
      #로그인이 성공했을 때
      session[:user_id] = user.id 
      redirect_to new_ingredient_path
  else
      #로그인이 실패했을 때
      flash[:alert] = '당신의 닉네임 또는 비밀번호가 잘못되었습니다'
      render 'new' 
  end
end

def destroy
  session.delete(:user_id)
  @current_user = nil
  redirect_to root_path
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params) 
        if @user.save #회원가입 성공했을 때 
            login_url(@user)
            redirect_to new_ingredient_path
        else #회원가입 실패했을 때 
            render "new"
        end
    end
    
    def edit
        current_user.add_role :admin
        redirect_to root_path
    end
    
    private
    def user_params
        params.require(:user).permit(:nickname, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def login_url(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
    
    # def current_user
    #     if @current_user.nil
    #         @current_user = User.find_by(id: session[:user_id])
    #     else
    #         @current_user = @current_user
    #     end
    # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/infos/aboutus.html.erb
<br><br>

<h1>Infos#aboutus</h1>
<p>Find me in app/views/infos/aboutus.html.erb</p>

app/views/infos/contact.html.erb
<br> <br>

<h1>Infos#contact</h1>
<p>Find me in app/views/infos/contact.html.erb</p>

app/views/ingredients/create.html.erb
<%# @ingredients.each do |i| %>

    <%#= i.s_category.to_s %> <br>
        
        <%#= Ingredient.check(i.s_ingred) %>
            <%# ingre = @ingredients.s_ingred %>
            <%# ingre = @ingredients.where("s_category = ?", c) %>
            <%#= ingre %> <br>
          <%# end %>
<%# end %>
<br><br>

<!--def self.where(category, name)-->
    <!--.where("category = ?", name)-->

app/views/ingredients/edit.html.erb
<h1>헬로우 고스트</h1>

app/views/ingredients/edit1.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-2.1.0.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>


            


    <%= form_for @ingredient, method: :post do |f| %>
    
     <%= f.submit "", :type => :image, :src => image_path('vegetable_recipe.png'), class: "col-xs-2 submitt" %>
        
        <div class="container">
        <div class="row">
            <% @items.each do |i| %>
                <div class="col-xs-3">
                  <hr> <h3 class="w700"> <%= i.ss_category %> </h3><br>
                  <div class="btn-group btn-group-vertical" data-toggle="buttons">
                      <% i.ss_ingred.split(',').each do |ingr| %>
                        <label class="btn">
                          
                          <%= f.check_box :s_ingred, { :multiple => true }, ingr, nil %> <i class="fa fa-square-o fa-2x"></i>
                          <i class="fa fa-check-square-o fa-2x"></i> <span> <%= f.label ingr %> </span>
                        </label>
                    <% end %>
                  </div>
                </div>
            <% end %>
          </div>
        <%#= f.submit '저장', class: 'btn btn-primary btn-lg' %>
            


    <% end %>
</div>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>

app/views/ingredients/new.html.erb
<br> <br> <br>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-2.1.0.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>


            


    <%= form_for @ingredient, method: :post do |f| %>
    
     <%= f.submit "", :type => :image, :src => image_path('vegetable_recipe.png'), class: "col-xs-2 submitt" %>
        
        <div class="container">
        <div class="row">
            <% @items.each do |i| %>
                <div class="col-xs-3">
                  <hr> <h3 class="w700" style="background-color: #028482; color: white;"> &nbsp; <%= i.ss_category %> </h3><br>
                  <div class="btn-group btn-group-vertical" data-toggle="buttons">
                      <% i.ss_ingred.split(',').each do |ingr| %>
                        <label class="btn">
                          <% if @a != [] %>
                              <% @a.each do |a| %>
                                  
                                      <% if a.s_ingred.split(',').include?(ingr) %>
                                        
                                        <%= f.check_box :s_ingred, { :multiple => true, checked: true }, ingr, nil %>
                                      <% else %>
                                        
                                        <%= f.check_box :s_ingred, { :multiple => true }, ingr, nil %>
                                      <% end %>
                                  
                              <% end %>
                          <% else %>
                          <%= f.check_box :s_ingred, { :multiple => true }, ingr, nil %>
                          <% end %>

                          
 <i class="fa fa-square-o fa-2x"></i>
                          <i class="fa fa-check-square-o fa-2x"></i> <span> <%= f.label ingr %> </span>
                        </label>
                    <% end %>
                  </div>
                </div>
            <% end %>
          </div>
        <%#= f.submit '저장', class: 'btn btn-primary btn-lg' %>
            


    <% end %>
</div>

app/views/ingredients/show.html.erb
<br> <br> <br>

<div class='container'>
    
    <% n=0 %>
    
    <% @selected_pick.each do |p| %>
        
    <!--=== Custom Content ===-->
    <% if n%3 == 0 %>    
        <div class='row'>
    <% end %>        
    
        <!--=== Content 1 ===-->
        <div class="col-sm-4">
            <div class="thumbnail custom-content">
                
                <% if p[0].img_link == "" %>
                    <%= link_to image_tag('nophoto.jpg', class: "recipe_image"), p[0].link, target: :_blank %>
                <% else %>
                    <%= link_to image_tag(p[0].img_link, class: "recipe_image"), p[0].link, target: :_blank %>    
                <% end %>
                
                
            
                <div class="caption">
                    <h4><%= link_to p[0].title, p[0].link, target: :_blank %></h4>
                    <p>선택한 재료와 <%= p[1].round(2)*100 %>% 일치 | 스크랩 횟수: <%= p[0].s_count %></p>
                    <h4>재료:</h4>
                    <% p[0].ingred.gsub(/\"/, '').sub(/\[/,'').sub(/\]/,'').gsub(/ /,'').split(',').each do |a| %>
                        <%= a %>
                        <% end %>
                </div>
            </div><!-- /thumbnail -->
        </div>
    <% if n%3 == 2 %>    
        </div>
    <% end %> 
    <% n+=1 %>
    <!-- /column -->
    <!-- /row -->
    <!--=== End Custom Content ===-->
    
    <% end %>    
    </div>

    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>오늘의메뉴</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= favicon_link_tag 'favicon.ico' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
  <%= csrf_meta_tags %>
</head>

<body>
  
  
  <div class="navbar navbar-default navbar-fixed-top" >
    <div class="container" >

        <div class="navbar-header">
            <button button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" rel="home" href="#" title="Buy Sell Rent Everyting">
                <img style="max-width: 130px; margin-top: -7px;"
                     src="<%= image_path('name.png')%>">
            </a>
        </div>
        
        <div id="navbar" class="collapse navbar-collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
                <% if current_user %>
                      <li><a href=""><%= current_user.nickname %>님</a></li>
                      <li class="active"><a href="/ingredients/new">Select Ingredients</a></li>
                      <li><a href="/infos/aboutus">About Us</a></li>
                      <li><a href="/infos/contact">Contact</a></li>
                      <%#= link_to '어드민권한', edit_ingredient_path(current_user.id) %>
                      <li><a href="<%= session_path(current_user.id) %>", data-method="delete">Log Out</a></li>
                    <% else %>
                      <li class="active"><a href="/ingredients/new">Select Ingredients</a></li>
                      <li><a href="/infos/aboutus">About Us</a></li>
                      <li><a href="/infos/contact">Contact</a></li>
                      <li><a href="<%= new_user_path %>">Sign Up</a></li>
                      <li><a href="<%= new_session_path %>">Log In</a></li>    | 
                    <% end %>
                
                <!--<li class="dropdown">-->
                <!--    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
                <!--    <ul class="dropdown-menu">-->
                <!--        <li><a href="#">Action</a></li>-->
                <!--        <li><a href="#">Another action</a></li>-->
                <!--        <li><a href="#">Something else here</a></li>-->
                <!--        <li role="separator" class="divider"></li>-->
                <!--        <li class="dropdown-header">Nav header</li>-->
                <!--        <li><a href="#">Separated link</a></li>-->
                <!--        <li><a href="#">One more separated link</a></li>-->
                <!--    </ul>-->
                <!--</li>-->
            </ul>
			<form class="navbar-form navbar-right" role="search" method="get" id="searchform" action="">
				<div class="form-group">
					<input name="s" id="s" type="text" class="search-query form-control" autocomplete="off" placeholder="Search...">
				</div>
			</form>
		</div>

    </div>
</div>

  
  


<%= yield %>

</body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

<% @img_link_temp.each do |t| %>
<%= t %>
<% end %>
<br>
<% @Items.each do |item| %>
    <h3>카테고리:</h3> <%= item.ss_category %><br>
    <h3>재료명:</h3> <%= item.ss_ingred %>
    <br> <br>
    "<%= item.ss_category %>", <%= item.ss_ingred %>
    <br><br><br><br>
    
<% end %>
<hr>
<% @recipes.each do |i| %>
    
    <h3>요리명:</h3> <%= i.title %> <br>
    <h3>이미지: </h3><%= image_tag i.img_link, size: "200x80", class:"img-thumbnail"%>
    <h3>재료 리스트:</h3> <%= i.ingred %> <br>
    <h3>링크:</h3> <%= i.link %> <br>
    <h3>스크랩 횟수:</h3> <%= i.s_count %> <br>
<% end %>

app/views/recipes/practice.html.erb
<% @selected_pick.each do |p| %>
    <%= p %> <br>
<% end %>    

app/views/recipes/show.html.erb
<%= @selected_pick.each do |p| %>

<!--=== Custom Content ===-->
<div class="row">
    <!--=== Content 1 ===-->
    <div class="col-sm-4">
        <div class="thumbnail custom-content">
            <%= image_tag p[0].img_link, alt: "이미지 없음" %>
            <div class="caption">
                <h4><a href=<% p[0].link %>><%= p[0].title %></a></h4>
                <p><%= p[1] %>% 일치</p>
                <p><%= p[0].ingred %></p>
                
            </div>
        </div><!-- /thumbnail -->
    </div><!-- /column -->
</div><!-- /row -->
<!--=== End Custom Content ===-->

<% end %>    

app/views/users/new.html.erb
<div class="logmod">
  <div class="logmod__wrapper">
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-1"><a href="<%= new_user_path %>">Sign Up</a></li>
        <li data-tabtar="lgm-2"><a href="<%= new_session_path %>">Login</a></li>
      </ul>
      <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your personal details <strong>to create an acount</strong></span>
        </div>
        <div class="logmod__form">
          <%= form_for @user, class: "simform" do |f| %>
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Nickname*</label>
                <%= f.text_field :nickname, class: "string optional", maxlength: "255", id: "user-email", placeholder: "Nickname", type: "string", size: "50" %>
              </div>
            </div>
            <div class="sminputs">
              <div class="input string optional">
                <label class="string optional" for="user-pw">Password *</label>
                <%= f.password_field :password, class: "string optional", maxlength: "255", id: "user-pw", placeholder: "Password", type: "text", size: "50"  %>
              </div>
              <div class="input string optional">
                <label class="string optional" for="user-pw-repeat">Repeat password *</label>
                <%= f.password_field :password_confirmation, class: "string optional", maxlength: "255", id: "user-pw-repeat", placeholder: "Repeat password", type: "text", size: "50" %>
              </div>
            </div>
            <div class="simform__actions">
              <%= f.submit 'SIGNUP' %>
            </div> 
          <% end %>
        </div> 
      </div>
      

  
      
      
      
      </div>
    </div>
  </div>
</div>






<script>

var LoginModalController = {
    tabsElementName: ".logmod__tabs li",
    tabElementName: ".logmod__tab",
    inputElementsName: ".logmod__form .input",
    hidePasswordName: ".hide-password",
    
    inputElements: null,
    tabsElement: null,
    tabElement: null,
    hidePassword: null,
    
    activeTab: null,
    tabSelection: 0, // 0 - first, 1 - second
    
    findElements: function () {
        var base = this;
        
        base.tabsElement = $(base.tabsElementName);
        base.tabElement = $(base.tabElementName);
        base.inputElements = $(base.inputElementsName);
        base.hidePassword = $(base.hidePasswordName);
        
        return base;
    },
    
    setState: function (state) {
    	var base = this,
            elem = null;
        
        if (!state) {
            state = 0;
        }
        
        if (base.tabsElement) {
        	elem = $(base.tabsElement[state]);
            elem.addClass("current");
            $("." + elem.attr("data-tabtar")).addClass("show");
        }
  
        return base;
    },
    
    getActiveTab: function () {
        var base = this;
        
        base.tabsElement.each(function (i, el) {
           if ($(el).hasClass("current")) {
               base.activeTab = $(el);
           }
        });
        
        return base;
    },
   
    addClickEvents: function () {
    	var base = this;
        
        base.hidePassword.on("click", function (e) {
            var $this = $(this),
                $pwInput = $this.prev("input");
            
            if ($pwInput.attr("type") == "password") {
                $pwInput.attr("type", "text");
                $this.text("Hide");
            } else {
                $pwInput.attr("type", "password");
                $this.text("Show");
            }
        });
 
        // base.tabsElement.on("click", function (e) {
        //     var targetTab = $(this).attr("data-tabtar");
            
        //     e.preventDefault();
        //     base.activeTab.removeClass("current");
        //     base.activeTab = $(this);
        //     base.activeTab.addClass("current");
            
        //     base.tabElement.each(function (i, el) {
        //         el = $(el);
        //         el.removeClass("show");
        //         if (el.hasClass(targetTab)) {
        //             el.addClass("show");
        //         }
        //     });
        // });
        
        base.inputElements.find("label").on("click", function (e) {
           var $this = $(this),
               $input = $this.next("input");
            
            $input.focus();
        });
        
        return base;
    },
    
    initialize: function () {
        var base = this;
        
        base.findElements().setState().getActiveTab().addClickEvents();
    }
};

$(document).ready(function() {
    LoginModalController.initialize();
});
  
  
  
  
  
</script>